# yaml-language-server: $schema=https://golangci-lint.run/jsonschema/golangci.jsonschema.json
run:
  timeout: 5m

linters:
  disable-all: true
  enable:
    - govet
    - staticcheck
    - unused
    - gosimple
    - ineffassign
