version: "2"
linters:
  default: none
  enable:
    - govet
    - ineffassign
    - staticcheck
    - unused
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - internal/di
      - third_party$
      - builtin$
      - examples$
formatters:
  exclusions:
    generated: lax
    paths:
      - internal/di
      - third_party$
      - builtin$
      - examples$
