// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "email": "support@paasdeploy.io"
        },
        "license": {
            "name": "MIT",
            "url": "https://opensource.org/licenses/MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/apps": {
            "get": {
                "description": "Retorna lista de apps cadastrados no sistema",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "apps"
                ],
                "summary": "Lista todas as aplicacoes",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/docs.App"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorInfo"
                        }
                    }
                }
            },
            "post": {
                "description": "Cadastra um novo app para deploy automatico",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "apps"
                ],
                "summary": "Cria uma nova aplicacao",
                "parameters": [
                    {
                        "description": "Dados do app",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/docs.CreateAppInput"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/docs.App"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorInfo"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorInfo"
                        }
                    }
                }
            }
        },
        "/apps/{id}": {
            "get": {
                "description": "Retorna os detalhes de um app especifico",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "apps"
                ],
                "summary": "Busca uma aplicacao por ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID do app",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/docs.App"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorInfo"
                        }
                    }
                }
            },
            "delete": {
                "description": "Deleta um app e remove o webhook associado",
                "tags": [
                    "apps"
                ],
                "summary": "Remove uma aplicacao",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID do app",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorInfo"
                        }
                    }
                }
            }
        },
        "/apps/{id}/deployments": {
            "get": {
                "description": "Retorna historico de deploys de um app",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "deployments"
                ],
                "summary": "Lista deploys de uma aplicacao",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID do app",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/docs.Deployment"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorInfo"
                        }
                    }
                }
            }
        },
        "/apps/{id}/redeploy": {
            "post": {
                "description": "Inicia um deploy manual do app",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "deployments"
                ],
                "summary": "Dispara um novo deploy",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID do app",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Commit SHA opcional",
                        "name": "input",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/handler.RedeployInput"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/docs.Deployment"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorInfo"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorInfo"
                        }
                    }
                }
            }
        },
        "/apps/{id}/rollback": {
            "post": {
                "description": "Reverte para o ultimo deploy bem-sucedido",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "deployments"
                ],
                "summary": "Faz rollback do deploy",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID do app",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/docs.Deployment"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorInfo"
                        }
                    }
                }
            }
        },
        "/apps/{id}/webhook": {
            "post": {
                "description": "Cria webhook automatico no repositorio GitHub",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "apps"
                ],
                "summary": "Configura webhook do GitHub",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID do app",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/docs.SetupResult"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorInfo"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorInfo"
                        }
                    }
                }
            },
            "delete": {
                "description": "Deleta webhook do repositorio GitHub",
                "tags": [
                    "apps"
                ],
                "summary": "Remove webhook do GitHub",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID do app",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorInfo"
                        }
                    }
                }
            }
        },
        "/apps/{id}/webhook/status": {
            "get": {
                "description": "Retorna o status do webhook configurado",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "apps"
                ],
                "summary": "Verifica status do webhook",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID do app",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/docs.WebhookStatus"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorInfo"
                        }
                    }
                }
            }
        },
        "/webhooks/github": {
            "post": {
                "description": "Endpoint que recebe push events do GitHub para disparar deploys automaticos",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "webhooks"
                ],
                "summary": "Recebe eventos do GitHub",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Tipo do evento (push, ping)",
                        "name": "X-GitHub-Event",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Assinatura HMAC-SHA256",
                        "name": "X-Hub-Signature-256",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "ID unico da entrega",
                        "name": "X-GitHub-Delivery",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Payload do evento",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github.PushEvent"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Evento processado (ping ou branch ignorado)",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "202": {
                        "description": "Deploy iniciado",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Payload invalido",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Assinatura invalida",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "docs.App": {
            "description": "Aplicacao cadastrada para deploy automatico",
            "type": "object",
            "properties": {
                "branch": {
                    "type": "string",
                    "example": "main"
                },
                "config": {
                    "type": "object"
                },
                "createdAt": {
                    "type": "string"
                },
                "id": {
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                },
                "lastDeployedAt": {
                    "type": "string"
                },
                "name": {
                    "type": "string",
                    "example": "my-app"
                },
                "repositoryUrl": {
                    "type": "string",
                    "example": "https://github.com/owner/repo.git"
                },
                "status": {
                    "type": "string",
                    "enum": [
                        "active",
                        "inactive",
                        "deleted"
                    ],
                    "example": "active"
                },
                "updatedAt": {
                    "type": "string"
                },
                "webhookId": {
                    "type": "integer",
                    "example": 123456789
                },
                "workdir": {
                    "type": "string",
                    "example": "."
                }
            }
        },
        "docs.CreateAppInput": {
            "description": "Dados necessarios para cadastrar um novo app",
            "type": "object",
            "required": [
                "name",
                "repositoryUrl"
            ],
            "properties": {
                "branch": {
                    "type": "string",
                    "example": "main"
                },
                "config": {
                    "type": "object"
                },
                "name": {
                    "type": "string",
                    "example": "my-app"
                },
                "repositoryUrl": {
                    "type": "string",
                    "example": "https://github.com/owner/repo.git"
                },
                "workdir": {
                    "type": "string",
                    "example": "."
                }
            }
        },
        "docs.Deployment": {
            "description": "Registro de um deploy realizado",
            "type": "object",
            "properties": {
                "appId": {
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                },
                "commitMessage": {
                    "type": "string",
                    "example": "feat: add new feature"
                },
                "commitSha": {
                    "type": "string",
                    "example": "abc123def456"
                },
                "createdAt": {
                    "type": "string"
                },
                "currentImageTag": {
                    "type": "string"
                },
                "errorMessage": {
                    "type": "string"
                },
                "finishedAt": {
                    "type": "string"
                },
                "id": {
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                },
                "logs": {
                    "type": "string"
                },
                "previousImageTag": {
                    "type": "string"
                },
                "startedAt": {
                    "type": "string"
                },
                "status": {
                    "type": "string",
                    "enum": [
                        "pending",
                        "running",
                        "success",
                        "failed",
                        "cancelled"
                    ],
                    "example": "success"
                }
            }
        },
        "docs.ErrorInfo": {
            "description": "Detalhes do erro",
            "type": "object",
            "properties": {
                "code": {
                    "type": "string",
                    "example": "NOT_FOUND"
                },
                "details": {},
                "message": {
                    "type": "string",
                    "example": "resource not found"
                }
            }
        },
        "docs.SetupResult": {
            "description": "Resultado da configuracao do webhook",
            "type": "object",
            "properties": {
                "active": {
                    "type": "boolean",
                    "example": true
                },
                "provider": {
                    "type": "string",
                    "example": "github"
                },
                "webhookId": {
                    "type": "integer",
                    "example": 123456789
                }
            }
        },
        "docs.WebhookStatus": {
            "description": "Status atual do webhook configurado",
            "type": "object",
            "properties": {
                "active": {
                    "type": "boolean",
                    "example": true
                },
                "error": {
                    "type": "string"
                },
                "exists": {
                    "type": "boolean",
                    "example": true
                },
                "lastPingAt": {
                    "type": "string"
                }
            }
        },
        "github.Commit": {
            "type": "object",
            "properties": {
                "added": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "author": {
                    "$ref": "#/definitions/github.CommitUser"
                },
                "committer": {
                    "$ref": "#/definitions/github.CommitUser"
                },
                "distinct": {
                    "type": "boolean"
                },
                "id": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "modified": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "removed": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "timestamp": {
                    "type": "string"
                },
                "tree_id": {
                    "type": "string"
                },
                "url": {
                    "type": "string"
                }
            }
        },
        "github.CommitUser": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "github.PushEvent": {
            "type": "object",
            "properties": {
                "after": {
                    "type": "string"
                },
                "before": {
                    "type": "string"
                },
                "commits": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github.Commit"
                    }
                },
                "compare": {
                    "type": "string"
                },
                "created": {
                    "type": "boolean"
                },
                "deleted": {
                    "type": "boolean"
                },
                "forced": {
                    "type": "boolean"
                },
                "head_commit": {
                    "$ref": "#/definitions/github.Commit"
                },
                "pusher": {
                    "$ref": "#/definitions/github.Pusher"
                },
                "ref": {
                    "type": "string"
                },
                "repository": {
                    "$ref": "#/definitions/github.Repository"
                },
                "sender": {
                    "$ref": "#/definitions/github.User"
                }
            }
        },
        "github.Pusher": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "github.Repository": {
            "type": "object",
            "properties": {
                "clone_url": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "default_branch": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "fork": {
                    "type": "boolean"
                },
                "full_name": {
                    "type": "string"
                },
                "git_url": {
                    "type": "string"
                },
                "html_url": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "node_id": {
                    "type": "string"
                },
                "owner": {
                    "$ref": "#/definitions/github.User"
                },
                "private": {
                    "type": "boolean"
                },
                "pushed_at": {
                    "type": "string"
                },
                "ssh_url": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "url": {
                    "type": "string"
                }
            }
        },
        "github.User": {
            "type": "object",
            "properties": {
                "avatar_url": {
                    "type": "string"
                },
                "html_url": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "login": {
                    "type": "string"
                },
                "node_id": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "handler.RedeployInput": {
            "type": "object",
            "properties": {
                "commitSha": {
                    "type": "string",
                    "example": "abc123def"
                }
            }
        }
    },
    "tags": [
        {
            "description": "Gerenciamento de aplicacoes",
            "name": "apps"
        },
        {
            "description": "Gerenciamento de deploys",
            "name": "deployments"
        },
        {
            "description": "Webhooks do GitHub",
            "name": "webhooks"
        }
    ]
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/paas-deploy/v1",
	Schemes:          []string{"http", "https"},
	Title:            "FlowDeploy API",
	Description:      "API para gerenciamento de aplicacoes e deploys automaticos",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
