// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/paasdeploy/backend/internal/engine"
	"github.com/paasdeploy/backend/internal/handler"
	"github.com/paasdeploy/backend/internal/repository"
	"github.com/paasdeploy/backend/internal/server"
)

import (
	_ "github.com/lib/pq"
)

// Injectors from wire.go:

func InitializeApplication() (*Application, func(), error) {
	config, err := ProvideConfig()
	if err != nil {
		return nil, nil, err
	}
	logger := ProvideLogger(config)
	db, cleanup, err := ProvideDatabase(config)
	if err != nil {
		return nil, nil, err
	}
	postgresAppRepository := repository.NewPostgresAppRepository(db)
	postgresEnvVarRepository := repository.NewPostgresEnvVarRepository(db)
	postgresCustomDomainRepository := repository.NewPostgresCustomDomainRepository(db)
	appClient := ProvideGitHubAppClient(config, logger)
	postgresInstallationRepository := repository.NewPostgresInstallationRepository(db)
	gitTokenProvider := ProvideGitTokenProvider(appClient, postgresInstallationRepository, logger)
	engineEngine := engine.New(config, db, postgresAppRepository, postgresEnvVarRepository, postgresCustomDomainRepository, gitTokenProvider, logger)
	serverConfig := ProvideServerConfig(config)
	serverServer := server.New(serverConfig, logger)
	healthHandler := ProvideHealthHandler()
	postgresDeploymentRepository := repository.NewPostgresDeploymentRepository(db)
	manager := ProvideWebhookManager(config, logger)
	appCleaner := ProvideAppCleaner(config, logger)
	appService := ProvideAppService(postgresAppRepository, postgresDeploymentRepository, postgresEnvVarRepository, manager, appCleaner, logger)
	appHandler := handler.NewAppHandler(appService)
	sseHandler := handler.NewSSEHandler()
	swaggerHandler := handler.NewSwaggerHandler()
	envVarHandler := handler.NewEnvVarHandler(postgresEnvVarRepository, postgresAppRepository)
	containerHealthHandler := handler.NewContainerHealthHandler(postgresAppRepository, engineEngine)
	appAdminHandler := ProvideAppAdminHandler(postgresAppRepository, engineEngine, config)
	webhookHandler := ProvideGitHubWebhookHandler(config, postgresAppRepository, postgresDeploymentRepository, logger)
	oAuthClient := ProvideOAuthClient(config, logger)
	postgresUserRepository := repository.NewPostgresUserRepository(db)
	postgresSessionRepository := repository.NewPostgresSessionRepository(db)
	tokenEncryptor := ProvideTokenEncryptor(config, logger)
	authHandler := ProvideAuthHandler(config, oAuthClient, postgresUserRepository, postgresSessionRepository, tokenEncryptor, logger)
	gitHubHandler := ProvideGitHubHandler(config, appClient, postgresInstallationRepository, postgresUserRepository, logger)
	authMiddleware := ProvideAuthMiddleware(config, postgresSessionRepository, postgresUserRepository, logger)
	postgresCloudflareConnectionRepository := repository.NewPostgresCloudflareConnectionRepository(db)
	cloudflareAuthHandler := ProvideCloudflareAuthHandler(config, postgresCloudflareConnectionRepository, tokenEncryptor, logger)
	domainHandler := ProvideDomainHandler(config, postgresAppRepository, postgresCustomDomainRepository, postgresCloudflareConnectionRepository, tokenEncryptor, engineEngine, logger)
	migrationHandler := ProvideMigrationHandler(logger)
	containerHandler := ProvideContainerHandler(engineEngine, logger)
	templateHandler := ProvideTemplateHandler(engineEngine, logger)
	certificateHandler := ProvideCertificateHandler(config, logger)
	application := &Application{
		Config:                 config,
		Logger:                 logger,
		DB:                     db,
		Engine:                 engineEngine,
		Server:                 serverServer,
		HealthHandler:          healthHandler,
		AppHandler:             appHandler,
		SSEHandler:             sseHandler,
		SwaggerHandler:         swaggerHandler,
		EnvVarHandler:          envVarHandler,
		ContainerHealthHandler: containerHealthHandler,
		AppAdminHandler:        appAdminHandler,
		WebhookHandler:         webhookHandler,
		AuthHandler:            authHandler,
		GitHubHandler:          gitHubHandler,
		AuthMiddleware:         authMiddleware,
		CloudflareAuthHandler:  cloudflareAuthHandler,
		DomainHandler:          domainHandler,
		MigrationHandler:       migrationHandler,
		ContainerHandler:       containerHandler,
		TemplateHandler:        templateHandler,
		CertificateHandler:     certificateHandler,
	}
	return application, func() {
		cleanup()
	}, nil
}
