// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/paasdeploy/backend/internal/agentdownload"
	"github.com/paasdeploy/backend/internal/engine"
	"github.com/paasdeploy/backend/internal/handler"
	"github.com/paasdeploy/backend/internal/repository"
	"github.com/paasdeploy/backend/internal/server"
)

// Injectors from wire.go:

func InitializeApplication() (*Application, func(), error) {
	config, err := ProvideConfig()
	if err != nil {
		return nil, nil, err
	}
	logger := ProvideLogger(config)
	db, cleanup, err := ProvideDatabase(config)
	if err != nil {
		return nil, nil, err
	}
	postgresAppRepository := repository.NewPostgresAppRepository(db)
	postgresEnvVarRepository := repository.NewPostgresEnvVarRepository(db)
	postgresCustomDomainRepository := repository.NewPostgresCustomDomainRepository(db)
	appClient := ProvideGitHubAppClient(config, logger)
	postgresInstallationRepository := repository.NewPostgresInstallationRepository(db)
	gitTokenProvider := ProvideGitTokenProvider(appClient, postgresInstallationRepository, logger)
	auditService := ProvideAuditService(db, logger)
	serverConfig := ProvideServerConfig(config)
	serverServer := server.New(serverConfig, logger)
	postgresCertificateAuthorityRepository := repository.NewPostgresCertificateAuthorityRepository(db)
	certificateAuthority, err := ProvidePKI(logger, postgresCertificateAuthorityRepository)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	postgresServerRepository := repository.NewPostgresServerRepository(db)
	agentClientForEngine := ProvideAgentClient(certificateAuthority, config)
	engineEngine := engine.New(engine.Params{
		Cfg:              config,
		DB:               db,
		AppRepo:          postgresAppRepository,
		EnvVarRepo:       postgresEnvVarRepository,
		CustomDomainRepo: postgresCustomDomainRepository,
		ServerRepo:       postgresServerRepository,
		AgentClient:      agentClientForEngine,
		GitTokenProvider: gitTokenProvider,
		AuditService:     auditService,
		Logger:           logger,
	})
	sseHandler := handler.NewSSEHandler()
	tokenStore := agentdownload.NewTokenStore()
	grpcserverServer := ProvideGrpcServer(config, certificateAuthority, postgresServerRepository, tokenStore, sseHandler, logger)
	healthHandler := ProvideHealthHandler()
	postgresDeploymentRepository := repository.NewPostgresDeploymentRepository(db)
	manager := ProvideWebhookManager(config, logger)
	appCleaner := ProvideAppCleaner(config, logger)
	appService := ProvideAppService(postgresAppRepository, postgresDeploymentRepository, postgresEnvVarRepository, manager, appCleaner, logger)
	appHandler := handler.NewAppHandler(appService, auditService, logger)
	swaggerHandler := handler.NewSwaggerHandler()
	envVarHandler := handler.NewEnvVarHandler(postgresEnvVarRepository, postgresAppRepository, logger)
	containerHealthHandler := handler.NewContainerHealthHandler(postgresAppRepository, postgresServerRepository, engineEngine, agentClientForEngine, config.GRPC.AgentPort, logger)
	appAdminHandler := ProvideAppAdminHandler(AppAdminHandlerDeps{
		AppRepo:          postgresAppRepository,
		ServerRepo:       postgresServerRepository,
		CustomDomainRepo: postgresCustomDomainRepository,
		EnvVarRepo:       postgresEnvVarRepository,
		Engine:           engineEngine,
		AgentClient:      agentClientForEngine,
		Config:           config,
		Logger:           logger,
	})
	postgresWebhookPayloadRepository := repository.NewPostgresWebhookPayloadRepository(db)
	webhookHandler := ProvideGitHubWebhookHandler(config, postgresAppRepository, postgresDeploymentRepository, postgresWebhookPayloadRepository, auditService, logger)
	oAuthClient := ProvideOAuthClient(config, logger)
	postgresUserRepository := repository.NewPostgresUserRepository(db)
	postgresSessionRepository := repository.NewPostgresSessionRepository(db)
	tokenEncryptor := ProvideTokenEncryptor(config, logger)
	authHandler := ProvideAuthHandler(config, oAuthClient, postgresUserRepository, postgresSessionRepository, tokenEncryptor, auditService, logger)
	gitHubHandler := ProvideGitHubHandler(config, appClient, postgresInstallationRepository, postgresUserRepository, logger)
	authMiddleware := ProvideAuthMiddleware(config, postgresSessionRepository, postgresUserRepository, logger)
	postgresCloudflareConnectionRepository := repository.NewPostgresCloudflareConnectionRepository(db)
	cloudflareAuthHandler := ProvideCloudflareAuthHandler(config, postgresCloudflareConnectionRepository, tokenEncryptor, logger)
	domainHandler := ProvideDomainHandler(DomainHandlerDeps{
		Config:         config,
		AppRepo:        postgresAppRepository,
		DomainRepo:     postgresCustomDomainRepository,
		ConnectionRepo: postgresCloudflareConnectionRepository,
		ServerRepo:     postgresServerRepository,
		TokenEncryptor: tokenEncryptor,
		Engine:         engineEngine,
		Logger:         logger,
	})
	migrationHandler := ProvideMigrationHandler(logger)
	containerHandler := ProvideContainerHandler(engineEngine, postgresServerRepository, agentClientForEngine, config, logger)
	containerExecHandler := ProvideContainerExecHandler(postgresServerRepository, agentClientForEngine, config, logger)
	templateHandler := ProvideTemplateHandler(engineEngine, logger)
	imageHandler := ProvideImageHandler(engineEngine, postgresServerRepository, agentClientForEngine, config, logger)
	certificateHandler := ProvideCertificateHandler(config, logger)
	auditHandler := ProvideAuditHandler(auditService, postgresWebhookPayloadRepository)
	resourceHandler := ProvideResourceHandler(engineEngine, postgresServerRepository, agentClientForEngine, config, logger)
	postgresNotificationChannelRepository := repository.NewPostgresNotificationChannelRepository(db)
	postgresNotificationRuleRepository := repository.NewPostgresNotificationRuleRepository(db)
	notificationService := ProvideNotificationService(postgresNotificationChannelRepository, postgresNotificationRuleRepository, postgresAppRepository, logger)
	notificationHandler := ProvideNotificationHandler(postgresNotificationChannelRepository, postgresNotificationRuleRepository, postgresAppRepository, logger)
	sshProvisioner := ProvideSSHProvisioner(certificateAuthority, config, logger, postgresServerRepository)
	healthChecker := ProvideAgentHealthChecker(agentClientForEngine, config)
	serverHandlerAgentDeps := ProvideServerHandlerAgentDeps(healthChecker, agentClientForEngine, config, grpcserverServer)
	serverHandler := ProvideServerHandler(postgresServerRepository, tokenEncryptor, sshProvisioner, sseHandler, serverHandlerAgentDeps, appService, logger)
	systemHandler := handler.NewSystemHandler()
	agentdownloadHandler := ProvideAgentDownloadHandler(tokenStore, config, logger)
	application := &Application{
		Config:                 config,
		Logger:                 logger,
		DB:                     db,
		Engine:                 engineEngine,
		Server:                 serverServer,
		GrpcServer:             grpcserverServer,
		HealthHandler:          healthHandler,
		AppHandler:             appHandler,
		SSEHandler:             sseHandler,
		SwaggerHandler:         swaggerHandler,
		EnvVarHandler:          envVarHandler,
		ContainerHealthHandler: containerHealthHandler,
		AppAdminHandler:        appAdminHandler,
		WebhookHandler:         webhookHandler,
		AuthHandler:            authHandler,
		GitHubHandler:          gitHubHandler,
		AuthMiddleware:         authMiddleware,
		CloudflareAuthHandler:  cloudflareAuthHandler,
		DomainHandler:          domainHandler,
		MigrationHandler:       migrationHandler,
		ContainerHandler:       containerHandler,
		ContainerExecHandler:   containerExecHandler,
		TemplateHandler:        templateHandler,
		ImageHandler:           imageHandler,
		CertificateHandler:     certificateHandler,
		AuditService:           auditService,
		AuditHandler:           auditHandler,
		ResourceHandler:        resourceHandler,
		NotificationService:    notificationService,
		NotificationHandler:    notificationHandler,
		ServerHandler:          serverHandler,
		SystemHandler:          systemHandler,
		AgentDownloadHandler:   agentdownloadHandler,
	}
	return application, func() {
		cleanup()
	}, nil
}
