// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/paasdeploy/backend/internal/engine"
	"github.com/paasdeploy/backend/internal/handler"
	"github.com/paasdeploy/backend/internal/repository"
	"github.com/paasdeploy/backend/internal/server"
)

import (
	_ "github.com/lib/pq"
)

// Injectors from wire.go:

func InitializeApplication() (*Application, func(), error) {
	config, err := ProvideConfig()
	if err != nil {
		return nil, nil, err
	}
	logger := ProvideLogger(config)
	db, cleanup, err := ProvideDatabase(config)
	if err != nil {
		return nil, nil, err
	}
	postgresAppRepository := repository.NewPostgresAppRepository(db)
	postgresEnvVarRepository := repository.NewPostgresEnvVarRepository(db)
	engineEngine := engine.New(config, db, postgresAppRepository, postgresEnvVarRepository, logger)
	serverConfig := ProvideServerConfig(config)
	serverServer := server.New(serverConfig, logger)
	healthHandler := ProvideHealthHandler()
	postgresDeploymentRepository := repository.NewPostgresDeploymentRepository(db)
	manager := ProvideWebhookManager(config, logger)
	appCleaner := ProvideAppCleaner(config, logger)
	appService := ProvideAppService(postgresAppRepository, postgresDeploymentRepository, postgresEnvVarRepository, manager, appCleaner, logger)
	appHandler := handler.NewAppHandler(appService)
	sseHandler := handler.NewSSEHandler()
	swaggerHandler := handler.NewSwaggerHandler()
	envVarHandler := handler.NewEnvVarHandler(postgresEnvVarRepository, postgresAppRepository)
	containerHealthHandler := handler.NewContainerHealthHandler(postgresAppRepository, engineEngine)
	webhookHandler := ProvideGitHubWebhookHandler(config, postgresAppRepository, postgresDeploymentRepository, logger)
	application := &Application{
		Config:                 config,
		Logger:                 logger,
		DB:                     db,
		Engine:                 engineEngine,
		Server:                 serverServer,
		HealthHandler:          healthHandler,
		AppHandler:             appHandler,
		SSEHandler:             sseHandler,
		SwaggerHandler:         swaggerHandler,
		EnvVarHandler:          envVarHandler,
		ContainerHealthHandler: containerHealthHandler,
		WebhookHandler:         webhookHandler,
	}
	return application, func() {
		cleanup()
	}, nil
}
